In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

print(a)
print(b)

print(a.shape)
print(b.shape)

print(a.ndim)
print(b.ndim)

print(a.dtype)
print(b.size)

[1 2 3]
[[1 2]
 [3 4]]
(3,)
(2, 2)
1
2
int64
4


In [ ]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(x.shape)
print(x.ndim)
print(x.size)

print(x[0])
print(x[1])
print(x[0, 1])
print(x[:, 0])
print(x[1, :])

(2, 3)
2
6
[1 2 3]
[4 5 6]
2
[1 4]
[4 5 6]


In [ ]:
x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(x[1,2]) 

print(x[:,0]) 

print(x[0,:]) 

print(x[:2,1:]) 


60
[10 40 70]
[10 20 30]
[[20 30]
 [50 60]]


In [ ]:

a = [1, 2, 3]
b = [4, 5, 6]

result = []
for i in range(len(a)):
    result.append(a[i] + b[i])
print(result)






SyntaxError: invalid character '＃' (U+FF03) (2604438960.py, line 1)

In [ ]:
#　NumPy vectorization:　calculate the whole array at once
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a @ b)  # dot product 
print(a + 10)  # broadcasting
print(np.sum(a))
print(np.mean(a))
print(np.max(a))

X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
w = np.array([0.5, -0.2])
print(X @ w)  # matrix-vector multiplication


[5 7 9]
[ 4 10 18]
32
[11 12 13]
6
2.0
3
[0.1 0.7 1.3]


In [ ]:

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A)
print(A.shape)

#reshape = change shape
B = A.reshape(3, 2)
print(B)
print(B.shape)

# transpose = swap axes
B = A.T
print(B)
print(B.shape)

In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [10, 20],
    [30, 40]
])

A * B
A @ B