In [10]:
import torch

X = torch.tensor([
    [0.0],
    [1.0],
    [2.0],
    [3.0],
    [4.0],
    [5.0]
])

y = torch.tensor([
    [0.0],
    [0.0],
    [0.0],
    [1.0],
    [1.0],
    [1.0]
])

# Initialize weights and bias
w = torch.tensor([[0.0]], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

# Compute the logits (linear combination of inputs and weights)
logits = X @ w + b

# Compute the predicted probabilities using the sigmoid function
p = torch.sigmoid(logits)

print("Logits:\n", logits)
print("Predicted probabilities:\n", p)

# Compute the binary cross-entropy loss
eps = 1e-7  # 防止 log(0) 的情况

loss = -(
    y * torch.log(p + eps)
    +
    (1 - y) * torch.log(1 - p + eps)
).mean()

print("Binary cross-entropy loss:", loss.item())

# Compute gradients
loss.backward()

print("Gradient of weights (w):", w.grad)
print("Gradient of bias (b):", b.grad)

learning_rate = 0.1

# Update weights and bias using gradient descent
with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad

print("Updated weights (w):", w)
print("Updated bias (b):", b)





Logits:
 tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)
Predicted probabilities:
 tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
Binary cross-entropy loss: 0.6931469440460205
Gradient of weights (w): tensor([[-0.7500]])
Gradient of bias (b): tensor([0.])
Updated weights (w): tensor([[0.0750]], requires_grad=True)
Updated bias (b): tensor([0.], requires_grad=True)


In [14]:
learning_rate = 0.1

for epoch in range(1000):
    # 1. Forward pass
    logits = X @ w + b

    # 2. Predicted probabilities
    p = torch.sigmoid(logits)

    # 3. Binary cross-entropy loss
    loss = -(
        y * torch.log(p + 1e-7)
        +
        (1-y) * torch.log(1-p + 1e-7)
    ).mean()

    # 4. Backward pass
    loss.backward()

    # 5. Update weights and bias using gradient descent
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # 6. Zero the gradients for the next iteration
    w.grad.zero_()
    b.grad.zero_()

In [16]:
predicted = (p >= 0.5).float()

print("Predicted labels:\n", predicted)

Predicted labels:
 tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
