In [ ]:
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()

print(iris.data.shape)
print(iris.target.shape)
print(iris.feature_names)
print(iris.target_names)

X = iris.data[:100, [0, 2]]
y = iris.target[:100]

print(X.shape)

(150, 4)
(150,)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
(100, 2)


In [ ]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=1,
    stratify=y
)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(70, 2)
(30, 2)
(70,)
(30,)


In [ ]:
import numpy as np

# Check the distribution of classes in the training and test sets
print(np.bincount(y_train))
print(np.bincount(y_test))

[35 35]
[15 15]


In [9]:
from sklearn.preprocessing import StandardScaler

# Standardize the features by removing the mean and scaling to unit variance
sc = StandardScaler()

# Fit the scaler on the training data and transform both training and test data
X_train_std = sc.fit_transform(X_train)

# Transform the test data using the same scaler
X_test_std = sc.transform(X_test)

print(X_train_std.mean(axis=0))  # Should be close to 0
print(X_train_std.std(axis=0))   # Should be close to 1

[ 2.36398203e-15 -2.42663033e-16]
[1. 1.]


In [ ]:
from sklearn.linear_model import LogisticRegression

# Create and train the logistic regression model
model = LogisticRegression()
model.fit(X_train_std, y_train)

print(model.coef_) # w1, w2 因为只有2个features
print(model.intercept_) # b

# Make predictions on the test set
pred = model.predict(X_test_std)

print(pred)
print(y_test)
print(model.score(X_test_std, y_test)) # accuracy

[[0.77403211 2.88722421]]
[0.30794837]
[1 1 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0]
[1 1 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0]
1.0


In [18]:

x = X_test_std[0]
print(x)

# net input = w1 * x1 + w2 * x2 + b
z = model.decision_function([x])
z_manual = np.dot(model.coef_, x) + model.intercept_
print(z_manual)
print(z)

# Predict class probabilities
prob = model.predict_proba([x])
print(prob)

print(y_test[0])

[2.64570877 1.26432591]
[6.00620431]
[6.00620431]
[[0.00245737 0.99754263]]
1
