In [11]:
import numpy as np

X = np.array([
    [1.0, 2.0],
    [2.0, 1.0],
    [3.0, 3.0]
])

w = np.array([0.5, -0.3])
b = 0.2

z = X @ w + b
print(z)
print(z.shape)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

probabilities = sigmoid(z)
print(probabilities)
print(probabilities.shape)
print(sigmoid(0))

#predictions = (probabilities >= 0.5).astype(int)
predictions = np.where(probabilities >= 0.5, 1, 0)
print(predictions)

[0.1 0.9 0.8]
(3,)
[0.52497919 0.7109495  0.68997448]
(3,)
0.5
[1 1 1]
