In [4]:
import torch

A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [5, 6],
    [7, 8]
])

torch.matmul(A, B)

x = torch.tensor([[1., 2.]])
W = torch.tensor([
    [1., 3.],
    [2., 4.]
])
torch.matmul(x, W)

tensor([[ 5., 11.]])

In [ ]:
A = torch.tensor([
    [1,2,3],
    [4,5,6]
])
A.shape
A.T
A.T.shape

tensor([[1, 2, 3, 4, 5, 6]])

In [12]:
x = torch.arange(12)

x
x.reshape(3,4)
x.reshape(2,6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])