In [13]:
import sys
import torch

print(sys.executable)
print(torch.__version__)

/Users/dan/ai-learning/.venv/bin/python
2.2.2


In [ ]:
numbers = torch.tensor([10, 20, 30, 40, 50])

print(numbers)
print(numbers.shape)
print(numbers.size())

tensor([10, 20, 30, 40, 50])


In [12]:
print(numbers.dtype)
scores = torch.tensor([10.0, 20.0, 30.0, 40.0, 50.0])
print(scores)
print(scores.dtype)

torch.int64
tensor([10., 20., 30., 40., 50.])
torch.float32


In [14]:
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)
print(matrix.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [16]:
reshaped_matrix = matrix.reshape(3, 2)

print(reshaped_matrix)
print(reshaped_matrix.shape)

automatic_shape = matrix.reshape(3, -1)

print(automatic_shape)
print(automatic_shape.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [ ]:
print(torch.sum(matrix))

print(matrix.sum())

print(matrix.sum(dim=1))

print(matrix.sum(dim=0))

tensor(21)
tensor(21)
tensor([ 6, 15])
tensor([5, 7, 9])


In [20]:
float_matrix = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

print(float_matrix.mean())

print(float_matrix.mean(dim=0))

print(float_matrix.mean(dim=1))

tensor(3.5000)
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])


In [ ]:
#exercise
exercise = torch.tensor([
    [10, 20], 
    [30, 40], 
    [50, 60]
])

print(exercise.shape)
print(exercise.dtype)
reshaped_exercise = exercise.reshape(2, 3)
print(reshaped_exercise)
print(exercise.sum())
float_exercise = torch.tensor([
    [10.0, 20.0], 
    [30.0, 40.0], 
    [50.0, 60.0]
])
print(float_exercise.mean())  
print(float_exercise.mean(dim=0))
print(float_exercise.mean(dim=1))
print(float_exercise.sum(dim=0))

torch.Size([3, 2])
torch.int64
tensor([[10, 20, 30],
        [40, 50, 60]])
tensor(210)
tensor(35.)
tensor([30., 40.])
tensor([15., 35., 55.])


In [ ]:
import torch
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(x)
print(x[0])
print(x[2])
print(x[1,2])
print(x[2,1])

print(x[:,0])
print(x[:,1])
print(x[0,:])
#结束位置不包含
print(x[0:2,:])
print(x[:,1:3])

import numpy as np
a = torch.tensor([1,2,3])
b = a.numpy()
print(type(b))
print(b)

c = np.array([10,20,30])
d = torch.from_numpy(c)
print(type(d))
print(d)    


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor([7, 8, 9])
tensor(6)
tensor(8)
tensor([1, 4, 7])
tensor([2, 5, 8])
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])
<class 'numpy.ndarray'>
[1 2 3]
<class 'torch.Tensor'>
tensor([10, 20, 30])


In [23]:
#numpy() 和 from_numpy() 默认共享内存
import numpy as np
import torch

a = np.array([1, 2, 3])
b = torch.from_numpy(a)

a[0] = 100

print(a)
print(b)

[100   2   3]
tensor([100,   2,   3])
