In [ ]:
import numpy as np

X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

X.shape #(4, 3)
X.ndim # 2
X.size # 12
X.sum()


# axis=n 表示把这个 dimension 压掉。

#每一个 feature 的 sum
X.sum(axis=0) # array([22, 26, 30])
#每一个 sample 的 sum
X.sum(axis=1) # array([ 6, 15, 24, 33])

X.mean(axis=0) # array([5.5, 6.5, 7.5])
X.mean(axis=1) # array([ 2.,  5.,  8., 11.])

X.max(axis=0) # array([10, 11, 12])
X.max(axis=1) # array([ 3,  6,  9, 12])

X.std(axis=0) # array([3.35410197, 3.35410197, 3.35410197])



array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39],
       [50, 51, 52]])

In [15]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3]])
c = np.array([[1], [2], [3]])

a.shape #(3,)
b.shape #(1, 3)
c.shape #(3, 1)

(3, 1)

In [ ]:
# Broadcasting
X_standardized = (X - X.mean(axis=0)) / X.std(axis=0) 

X + 10  # (4, 3) +　scalar

X + np.array([10, 20, 30])  # (4, 3) + (3,)

X + np.array([[10], [20], [30], [40]]) # (4, 3) + (4, 1)

In [19]:
# Python loop
result = []
for row in X:
    result.append(row * 2)

print(result) # [array([ 2,  4,  6]), array([ 8, 10, 12]), array([14, 16, 18]), array([20, 22, 24])]

#Vectorization
result = X * 2
print(result) # [array([ 2,  4,  6]), array([ 8, 10, 12]), array([14, 16, 18]), array([20, 22, 24])]

[array([2, 4, 6]), array([ 8, 10, 12]), array([14, 16, 18]), array([20, 22, 24])]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [23]:
# Python loop
scores = []
for row in X:
    scores.append(row[0] * 0.2 +
                  row[1] * 0.5 +
                  row[2] * -0.1)
print(scores) 

# Vectorization
w = np.array([0.2, 0.5, -0.1])

scores = X @ w
print(scores) # [0.9 2.7 4.5 6.3]
print(X.dot(w)) # [0.9 2.7 4.5 6.3]
print(np.dot(X, w)) # [0.9 2.7 4.5 6.3]


print(X * w) 


[np.float64(0.8999999999999999), np.float64(2.6999999999999997), np.float64(4.5), np.float64(6.3)]
[0.9 2.7 4.5 6.3]
[0.9 2.7 4.5 6.3]
[0.9 2.7 4.5 6.3]
[[ 0.2  1.  -0.3]
 [ 0.8  2.5 -0.6]
 [ 1.4  4.  -0.9]
 [ 2.   5.5 -1.2]]
