In [ ]:
import numpy as np

X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

X.shape #(4, 3)
X.ndim # 2
X.size # 12
X.sum()


# axis=n 表示把这个 dimension 压掉。

#每一个 feature 的 sum
X.sum(axis=0) # array([22, 26, 30])
#每一个 sample 的 sum
X.sum(axis=1) # array([ 6, 15, 24, 33])

X.mean(axis=0) # array([5.5, 6.5, 7.5])
X.mean(axis=1) # array([ 2.,  5.,  8., 11.])

X.max(axis=0) # array([10, 11, 12])
X.max(axis=1) # array([ 3,  6,  9, 12])

X.std(axis=0) # array([3.35410197, 3.35410197, 3.35410197])



array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39],
       [50, 51, 52]])

In [15]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3]])
c = np.array([[1], [2], [3]])

a.shape #(3,)
b.shape #(1, 3)
c.shape #(3, 1)

(3, 1)

In [ ]:
# Broadcasting
X_standardized = (X - X.mean(axis=0)) / X.std(axis=0) 

X + 10  # (4, 3) +　scalar

X + np.array([10, 20, 30])  # (4, 3) + (3,)

X + np.array([[10], [20], [30], [40]]) # (4, 3) + (4, 1)

In [19]:
# Python loop
result = []
for row in X:
    result.append(row * 2)

print(result) # [array([ 2,  4,  6]), array([ 8, 10, 12]), array([14, 16, 18]), array([20, 22, 24])]

#Vectorization
result = X * 2
print(result) # [array([ 2,  4,  6]), array([ 8, 10, 12]), array([14, 16, 18]), array([20, 22, 24])]

[array([2, 4, 6]), array([ 8, 10, 12]), array([14, 16, 18]), array([20, 22, 24])]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [23]:
# Python loop
scores = []
for row in X:
    scores.append(row[0] * 0.2 +
                  row[1] * 0.5 +
                  row[2] * -0.1)
print(scores) 

# Vectorization
w = np.array([0.2, 0.5, -0.1])

scores = X @ w
print(scores) # [0.9 2.7 4.5 6.3]
print(X.dot(w)) # [0.9 2.7 4.5 6.3]
print(np.dot(X, w)) # [0.9 2.7 4.5 6.3]


print(X * w) 


[np.float64(0.8999999999999999), np.float64(2.6999999999999997), np.float64(4.5), np.float64(6.3)]
[0.9 2.7 4.5 6.3]
[0.9 2.7 4.5 6.3]
[0.9 2.7 4.5 6.3]
[[ 0.2  1.  -0.3]
 [ 0.8  2.5 -0.6]
 [ 1.4  4.  -0.9]
 [ 2.   5.5 -1.2]]


In [ ]:
# Week04 Day05 reshape

import numpy as np

a = np.arange(12)

print(a.shape) #(12,)
print(a) # [ 0  1  2  3  4  5  6  7  8  9 10 11]    

b = a.reshape(3, 4)
print(b.shape) #(3, 4)
print(b) 

c = a.reshape(2, 2, 3)
print(c.shape) #(2, 2, 3)
print(c)

d = a.reshape(2, -1) # -1 means "infer this dimension"
print(d.shape) #(2, 6)
print(d)

e = a.reshape(1, -1) 
print(e.shape) #(1, 12)
print(e)
print(a) # 注意(1, 12)和(12,)的区别，前者是二维数组，后者是一维数组

(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(1, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# Week04 Day05 transpose

import numpy as np

X = np.array([
    [1,2,3],
    [4,5,6]
])

X.shape
X.T.shape

# For 1D arrays, transpose has no effect
a = np.array([1,2,3])
print(a.shape) #(3,)
print(a.T.shape) #(3,)

(3,)
(3,)


In [24]:
# Week04 Day05 Boolean Indexing

import numpy as np

x = np.array([10, 20, 30, 40, 50])

# Boolean array
print(x > 25) # mask: [False False True  True  True]

# x[mask]
print(x[x > 25]) # [30 40 50]
print(x[x == 30])
print(x[x <= 30])

# Boolean indexing 不仅能读取，还可以修改
x[x > 30] = 0
print(x) # [10 20 30  0  0]

X = np.array([
    [1, 10],
    [2, 20],
    [3, 30],
    [4, 40]
]) 

#取所有 samples 的第 0 个 feature
print(X[:, 0]) #[1 2 3 4]

print(X[:, 0] > 2) # mask: [False False  True  True]

#选择 feature 0 大于 2 的所有 samples
print(X[X[:, 0] > 2]) 


[False False  True  True  True]
[30 40 50]
[30]
[10 20 30]
[10 20 30  0  0]
[1 2 3 4]
[False False  True  True]
[[ 3 30]
 [ 4 40]]


In [ ]:
# Week04 Day05 Copy vs View

import numpy as np

a = np.array([1,2,3,4,5])

#不是复制数据 copy，而是窗口 view
b = a[1:4]
print(b) # [2 3 4]
b[0] = 100
print(a) # [  1 100   3   4   5]  # a 被修改了

c = a[1:4].copy()
c[0] = 200
print(c) # [200   3   4]
print(a) # [  1 100   3   4   5]  # a 没有被修改

[2 3 4]
[  1 100   3   4   5]
[200   3   4]
[  1 100   3   4   5]


In [55]:
# Week04 Day05 Mini Exercise

import numpy as np

X = np.array([
    [170, 65, 30],
    [180, 85, 41],
    [160, 55, 25],
    [175, 73, 36],
    [168, 62, 28]
])

# 1. 取所有人的 height
height = X[:, 0]
print(height) # [170 180 160 175 168]

# 2. 取前 3 个 samples
print(X[:3,:])

# 3. 取 age > 30 的 samples
print(X[X[:,2]>30])

# 4. 计算每个 feature mean
print(X.mean(axis=0))

# 5. 对每个 feature standardize
X_standardized = (X - X.mean(axis=0)) / X.std(axis=0)
print(X_standardized)

# 6. 查看 standardized data 的 mean
print(X_standardized.mean(axis=0))

[170 180 160 175 168]
[[170  65  30]
 [180  85  41]
 [160  55  25]]
[[180  85  41]
 [175  73  36]]
[170.6  68.   32. ]
[[-0.08900862 -0.2919371  -0.34710507]
 [ 1.39446845  1.65431026  1.5619728 ]
 [-1.5724857  -1.26506078 -1.21486774]
 [ 0.65272991  0.48656184  0.69421013]
 [-0.38570404 -0.58387421 -0.69421013]]
[ 8.65973959e-16  2.22044605e-17 -4.44089210e-17]
