In [11]:
# L1 vs L2 Regularization

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

iris = load_iris()

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=1,
    stratify=y
)

sc = StandardScaler()

sc.fit(X_train)

X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

print(X_train_std.shape)
print(X_test_std.shape)

(105, 4)
(45, 4)


In [8]:
# L2 Logistic Regression
l2_model = LogisticRegression(
    penalty="l2",
    C=1.0,
    max_iter=1000
)

l2_model.fit(X_train_std, y_train)

# weights
print(l2_model.coef_)
print(l2_model.coef_.shape)

# bias
print(l2_model.intercept_)

[[-1.05625943  1.01448134 -1.7582251  -1.60043464]
 [ 0.22720684 -0.26607386 -0.13674912 -0.58305713]
 [ 0.8290526  -0.74840748  1.89497422  2.18349177]]
(3, 4)
[-0.24889218  1.84686139 -1.59796921]


/Users/dan/ai-learning/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(


In [9]:

for C in [100, 1, 0.01]:
    model = LogisticRegression(
        penalty="l2",
        C=C,
        max_iter=1000
    )

    model.fit(X_train_std, y_train)

    print("C =", C)
    print(model.coef_)
    print()

C = 100
[[-2.9011272   2.59464762 -5.251537   -4.74324085]
 [ 1.67487202 -0.22737422 -2.44970455 -2.00186868]
 [ 1.22625518 -2.3672734   7.70124155  6.74510953]]

C = 1
[[-1.05625943  1.01448134 -1.7582251  -1.60043464]
 [ 0.22720684 -0.26607386 -0.13674912 -0.58305713]
 [ 0.8290526  -0.74840748  1.89497422  2.18349177]]

C = 0.01
[[-0.17144674  0.16845868 -0.23863458 -0.22706891]
 [-0.01117876 -0.1584587   0.0494202   0.01655632]
 [ 0.18262551 -0.00999998  0.18921438  0.2105126 ]]



/Users/dan/ai-learning/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/dan/ai-learning/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/dan/ai-learning/.venv/l

In [15]:
for C in [100, 1, 0.01]:
    model = LogisticRegression(
        penalty="l1",
        C=C,
        solver="saga",
        max_iter=1000
    )

    model.fit(X_train_std, y_train)

    print("C =", C)
    print(model.coef_)
    print()

C = 100
[[-3.05234862  2.63596541 -6.47976034 -5.72360002]
 [ 1.10096725  0.         -2.28202206 -1.68779966]
 [ 0.43669976 -2.4620473  10.27464302  8.92850925]]

C = 1
[[ 0.          0.68508499 -4.56589694  0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.         -0.54594165  3.92785669  3.7011433 ]]

C = 0.01
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



/Users/dan/ai-learning/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/dan/ai-learning/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/dan/ai-learning/.venv/lib/python3.12/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/dan/ai-learning/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:14

In [18]:

l1_model = LogisticRegression(
    penalty="l1",
    C=0.01,
    solver="saga",
    max_iter=1000
)

l2_model = LogisticRegression(
    penalty="l2",
    C=0.01,
    max_iter=1000
)

l1_model.fit(X_train_std, y_train)
l2_model.fit(X_train_std, y_train)

print("L1 weights:")
print(l1_model.coef_)

print("L2 weights:")
print(l2_model.coef_)

L1 weights:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
L2 weights:
[[-0.17144674  0.16845868 -0.23863458 -0.22706891]
 [-0.01117876 -0.1584587   0.0494202   0.01655632]
 [ 0.18262551 -0.00999998  0.18921438  0.2105126 ]]


/Users/dan/ai-learning/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/dan/ai-learning/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/dan/ai-learning/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1